### ISSUE TITLE
Swift 3 Support? 

### ISSUE THREAD

**Issue by OmarBizreh** [MarioIannotta/MIAlertController#1]
Plans to support Swift 3?

**Comment by MarioIannotta** [comment]
I have already the swift 3 code with a new feature and some improvements. One of these days I'll push the branch and make the new pod.

The swift 3 pod is now available: `pod 'MIAlertController', '~> 1.3'`

**Comment by OmarBizreh** [comment]
Thank you

**Comment by OmarBizreh** [comment]
Great, will try it out now. Thank you for your support :)
