### ISSUE TITLE
Alert with two options: one above the other

### ISSUE THREAD

**Issue by davidseek** [MarioIannotta/MIAlertController#3]
How do I force the buttons to be arranged among themselves? Currently I can only archive that by setting up more buttons then needed

**Comment by MarioIannotta** [comment]
Hi, I don't understand what do you mean by "force the buttons to be arranged among themselves"?

**Comment by davidseek** [comment]
currently, the buttons are arranged next to each other if there are only two buttons with short texts like "ok", if I have like 3 or 4 buttons, they are arranged among themselves. but i want even just two buttons with short texts to be arranged among each other.

this problem appears only, if i use buttons with a config:

```
alertController.addButton(MIAlertController.Button(title: "Logout",
                                                           type: .default,
                                                           config: getMIAControllerButtonCfg(Colors.white),
                                                           action: {self.logout() }))
```

for example. if i use:

`MIAlertController.Button(title: "Option 1", action: {
                    print("option one selected")
                })`

like in the example project, the buttons are among themselves

**Comment by davidseek** [comment]
if the text is too short and i use only 2 buttons, they are next to each other

![simulator screen shot nov 20 2016 9 38 29 pm](https://cloud.githubusercontent.com/assets/17073950/20465974/b951b660-af69-11e6-9af2-cff770a5b57f.png)

if i add unneeded buttons like cancel:

![simulator screen shot nov 20 2016 7 41 09 pm](https://cloud.githubusercontent.com/assets/17073950/20465981/d0bd2c3a-af69-11e6-96fa-7d78c56f48ae.png)

**Comment by MarioIannotta** [comment]
Ok, now I get it.
There's not a "clean" solution (like changing a flag) because MIAlertController works just like UIAlertController:
- 2 options -> inline
- more than 3 options -> one above the other

Anyway you should be able to achieve the result you want by removing the lines from 307 to 334 of  `MIAlertController.swift`.

**Comment by davidseek** [comment]
thank you very much. love your framework btw. will try to find a way to have the min size of the view myself now. but then it fits PERFECTLY my needs

**Comment by MarioIannotta** [comment]
I'm glad to hear that, have a good day :)
